export { PropertyCard } from './ui/PropertyCard'
export { PropertyCardSkeleton } from './ui/PropertyCardSkeleton.tsx'
export type { TPropertyItem, TPropertyCategory } from './types'
export { useGetPropertyQuery, propertyApi } from './api/propertyApi.ts'
export { mockPropertyHandler } from './api/mockPropertyHandler.ts'
